experimentName: LSTM_Tune
searchSpaceFile: lstm_search_space.json
trialCommand: python lstm_tune.py
trialConcurrency: 1
maxTrialNumber: 20
trialGpuNumber: 1
maxExperimentDuration: 1h
experimentWorkingDirectory: D:\nni_experiments
tuner:
   name: TPE
   classArgs:
      optimize_mode: minimize
trainingService:
   platform: local
   useActiveGpu: True
