experimentName: GRU_Tune
searchSpaceFile: gru_search_space.json
trialCommand: python gru_tune.py
trialConcurrency: 1
maxTrialNumber: 100
trialGpuNumber: 1
maxExperimentDuration: 15h
experimentWorkingDirectory: D:\nni_experiments
tuner:
   name: TPE
   classArgs:
      optimize_mode: minimize
trainingService:
   platform: local
   useActiveGpu: True
